# Generated by Django 5.1.1 on 2024-10-09 13:27

from django.db import migrations

def migrate_author_to_contributors(apps, schema_editor):
    Blog = apps.get_model('blog', 'Blog')

    for blog in Blog.objects.all():
        if blog.author:
            # move contributor to intermediary table
            blog.contributors.add(blog.author,
                                  through_defaults={
                                      'contribution': 'Primary Author'
                                  })
        else:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blog_author_blogcontributor_blog_contributors'),
    ]

    operations = [
        migrations.RunPython(migrate_author_to_contributors)
    ]
