# Generated by Django 5.1.1 on 2024-09-25 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_band_limited_edition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='band',
            name='limited_edition',
        ),
    ]
