# Generated by Django 5.1.1 on 2024-09-26 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_merge_20240926_0108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='antiquity',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='limited_edition',
        ),
    ]
