# Generated by Django 5.1.3 on 2024-11-09 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('is_enabled', models.BooleanField(default=False)),
                ('dependencies', models.ManyToManyField(blank=True, to='app_installer.appconfig')),
            ],
            options={
                'permissions': [('can_access_app', 'Can access the app')],
            },
        ),
    ]
