# Generated by Django 5.1.1 on 2024-09-25 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_listing_band'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='limited_edition',
            field=models.BooleanField(default=False),
        ),
    ]
