# Generated by Django 5.1.1 on 2024-09-25 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_listing_antiquity'),
        ('listings', '0008_listing_limited_edition'),
    ]

    operations = [
    ]
